Packages in this repository
- Thermophysical and Thermochemical coefficients for gases and liquids
- Collision integrals

Package Thermophysical and Thermochemical coefficients for gases and
liquids contains data for:
- Density and specific volume
- C_p and C_v
- Enthalpy and entropy
- Internal energy and speed of sound
- Viscosity and thermal conductivity
- Joule-Thomson coefficient Surface tension (saturation curve only)

This package does not include ab-initio methods for calculating the
properties.  It only includes methods based on simple formulas or
table interpolation.

The data is obtained from on-line databases (such as the NIST webbook)
and journal articles

All internal calculations and all results are in SI.

Package for collision integrals gives fitting formulas for collision
integrals Omega-11 and Omega-22

* Status

  Fairly stable.  New features added as needed.

** Future plans
   I want to re-factor some of the features, such as collision
   integrals, which would be of use in other packages (such as the
   gas-kinetic formulary)

