Packages in this repository
- Thermophysical and Thermochemical coefficients for gases and liquids
- Collision integrals

Package Thermophysical and Thermochemical coefficients for gases and
liquids contains data for:
- Density and specific volume
- C_p and C_v
- Enthalpy and entropy
- Internal energy and speed of sound
- Viscosity and thermal conductivity
- Joule-Thomson coefficient Surface tension (saturation curve only)

This package does not include ab-initio methods for calculating the
properties.  It only includes methods based on simple formulas or
table interpolation.

The data is obtained from on-line databases (such as the NIST webbook)
and journal articles.

All internal calculations and all results are a mixture of SI and
chemistry friendly units - atomic mass units, etc.

Package for collision integrals
- Reads table of Lennard-Jones potential parameters
- Provides fitting formulas for collision integrals Omega-11 and
  Omega-22

This package is used by the transport coefficients.  As it is closer
to gas kinetic theory, it uses SI units (mass is in kg, cross-sections
in meters)  

* Warning
  Thermal conductivity calculated using Lennard-Jones collision
  integrals and Cv gives incorrect values for N2 by a factor of 1.25.
  The code gives correct values for Ar.

  I have tested the values of Cv for both Ar and N2 (which are
  calculated by the package).  I can't figure out where else the
  difference could originate form.

  
* Status

  Fairly stable, but lightly tested after recent refactoring of
  collision integrals.

  New features added as needed.


